from fastapi import APIRouter

from models.schemas import ReportRequest, ReportResponse

router = APIRouter(prefix="/report", tags=["report"])


@router.post("/", response_model=ReportResponse)
async def generate_report(request: ReportRequest):
    return ReportResponse(
        markdown=f"# Drug Repurposing Report: {request.disease}\n\n"
        "## Summary\nThis is a placeholder report generated by the mock endpoint.\n\n"
        "## Top Candidates\n- Dabrafenib (confidence: 0.85)\n- Vemurafenib (confidence: 0.78)\n"
    )
